pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:GDK/inno-setup-for-delphi-packages.git
          - cd inno-setup-for-delphi-packages.git
          - git push --mirror git@github.com:GDKsoftware/inno-setup-for-delphi-packages.git